---
- name: "Load {{ component }} variables"
  include_vars: "{{ component|lower }}.yml"

- name: "Get {{ component }} version {{ component_version }}"
  get_url:
    dest: "{{ dest_tarball }}"
    url: "{{ base_url }}/{{ release }}"
    checksum: "sha256:{{ base_url }}/{{ checksum }}"

- name: Extract binary from tarball
  unarchive:
    src: "{{ dest_tarball }}"
    remote_src: yes
    dest: "{{ base_dir }}"
    creates: "{{ absolute_path }}"

- name: "Create {{ component }} group"
  group:
    name: "{{ component }}"
    system: yes
    state: present
  become: yes

- name: "Create {{ component }} user"
  user:
    name: "{{ component }}"
    group: "{{ component }}"
    system: yes
    create_home: no
    shell: /usr/bin/nologin
    home: "{{ prometheus_db_dir | default(omit) }}"
  become: yes

- name: "Install {{ component }}"
  command: "install {{ absolute_path }}/{{ component }} /usr/local/bin"
  args:
    creates: "/usr/local/bin/{{ component }}"
  become: yes

- name: "Include {{ component }} specific tasks"
  include_tasks: "{{ component|lower }}.yml"
  when: component_tasks

- name: Create systemd service unit
  template:
    src: systemd.service.j2
    dest: "/usr/lib/systemd/system/{{ component }}.service"
    mode: 0644
  become: yes
  notify:
    - restart service
