---
- name: Ensure architecture naming conventions match
  include_vars: "{{ ansible_architecture|lower }}.yml"

- name: "Get node_exporter {{ \"%s%s\" | format('v',node_exporter_version) }}"
  get_url:
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    url: "https://github.com/prometheus/node_exporter/releases/download/{{ \"%s%s\" | format('v',node_exporter_version) }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    checksum: "sha256:https://github.com/prometheus/node_exporter/releases/download/{{ \"%s%s\" | format('v',node_exporter_version) }}/sha256sums.txt"
  register: tarball

- name: Extract binary from tarball
  unarchive:
    src: "{{ tarball.dest }}"
    remote_src: yes
    dest: /tmp
    creates: "{{ tarball.dest | splitext | first }}"

- name: Install node_exporter
  command: "install {{ tarball.dest | splitext | first | splitext | first }}/node_exporter /usr/local/bin"
  args:
    creates: /usr/local/bin/node_exporter
  become: yes
  #FIXME: filtering applied here is one of those flaming bags old man clemens put out with his boots.
