---
- name: Ensure architecture naming conventions match repository
  include_vars: "{{ ansible_architecture|lower }}.yml"

- name: "Load {{ component }} variables"
  include_vars: "{{ component|lower }}.yml"

- name: "Get {{ component }} version {{ component_version }}"
  get_url:
    dest: "{{ dest_tarball }}"
    url: "{{ base_url }}/{{ release }}"
    checksum: "sha256:{{ base_url }}/{{ checksum }}"

- name: Extract binary from tarball
  unarchive:
    src: "{{ dest_tarball }}"
    remote_src: yes
    dest: "{{ base_dir }}"
    creates: "{{ absolute_path }}"

- name: "Install {{ component }}"
  command: "install {{ absolute_path }}/{{ component }} /usr/local/bin"
  args:
    creates: "/usr/local/bin/{{ component }}"
  become: yes
