---
- name: Install promtool
  command: "install {{ absolute_path }}/promtool /usr/local/bin"
  args:
    creates: "/usr/local/bin/promtool"
  become: yes

- name: Install system configuration
  copy:
    src: "{{ absolute_path }}/{{ item }}"
    remote_src: yes
    dest: "{{ prometheus_config_dir }}/"
  with_items:
    - consoles
    - console_libraries
  become: yes

- name: Create data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: "{{ component }}"
    group: "{{ component }}"
    mode: 0755
  become: yes

- name: Install configuration file
  template:
    src: "{{ component }}.yml.j2"
    dest: "{{ prometheus_config_dir }}/{{ component }}.yml"
    owner: root
    group: "{{ component }}"
    mode: 0640
    validate: "{{ binary_install_dir }}/promtool check config %s"
  become: yes
  notify:
    - restart service
